spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order-service?createDatabaseIfNotExist=true
    username: root
    password:

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka